services:
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: access
      MINIO_ROOT_PASSWORD: secretsecret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    command: server /data --console-address ":9001"
  minio-test:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: access
      MINIO_ROOT_PASSWORD: secretsecret
    ports:
      - "9002:9000"
    command: server /data
volumes:
  minio:
