name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: arm64-beta

    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      minio:
        image: maragudk/minio-ci
        ports:
          - 9002:9000
        env:
          MINIO_ROOT_USER: access
          MINIO_ROOT_PASSWORD: secretsecret

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -coverprofile=cover.out -shuffle on ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
